#ifndef NAM_A2FULL_H
#define NAM_A2FULL_H

#include <stdint.h>

/* Generated by nam2c (--tiled) - do not edit */

/* 2: caller-owned instances (nam_a2full_t, nam_a2full_state_t, nam_a2full_weights_t). */
#define NAM_A2FULL_API_VERSION 2

#ifndef NAM_A2FULL_MAX_BUFFER_SIZE
#define NAM_A2FULL_MAX_BUFFER_SIZE 64
#endif

/* NAM_A2FULL_BLOCK_HINT: your usual num_frames per nam_a2full_process call. Define it when
   compiling the engine's .c file to pick the tile shapes for it; any value
   gives the same output. Default 48. */

/* NAM_WEIGHTS: section for the baked const capture (nam_a2full_builtin_weights). */
#ifndef NAM_WEIGHTS
#define NAM_WEIGHTS
#endif
#ifndef NAM_ALIGNED
  #if defined(__GNUC__)
    #define NAM_ALIGNED(n) __attribute__((aligned(n)))
  #else
    #define NAM_ALIGNED(n)
  #endif
#endif

#define NAM_A2FULL_IN_CHANNELS 1
#define NAM_A2FULL_OUT_CHANNELS 1
#define NAM_A2FULL_SAMPLE_RATE 48000.0f
/* Receptive field: samples of silence nam_a2full_prewarm() runs after a reset,
   as NeuralAmpModelerCore does (its WaveNet prewarm formula). */
#define NAM_A2FULL_PREWARM_SAMPLES 6347

/* A capture, packed into the kernels' layout. Read-only while processing,
   so any number of instances can share one. Hot: e.g. DTCM on Cortex-M7. */
typedef struct NAM_ALIGNED(32) nam_a2full_weights_t {
    float la0_w[12149];
    float head_scale;
} nam_a2full_weights_t;

/* Planar ring buffers: one row per channel of (lookback + NAM_A2FULL_MAX_BUFFER_SIZE)
   live columns plus a NAM_A2FULL_MAX_BUFFER_SIZE-column mirror. */
typedef struct nam_a2full_state_t {
    float la0_l0_rb[8 * (5 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l1_rb[8 * (15 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l2_rb[8 * (35 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l3_rb[8 * (85 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l4_rb[8 * (205 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l5_rb[8 * (505 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l6_rb[8 * (1195 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l7_rb[8 * (5 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l8_rb[8 * (15 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l9_rb[8 * (35 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l10_rb[8 * (85 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l11_rb[8 * (205 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l12_rb[8 * (505 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l13_rb[8 * (1195 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l14_rb[8 * (14 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l15_rb[8 * (182 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l16_rb[8 * (5 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l17_rb[8 * (15 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l18_rb[8 * (35 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l19_rb[8 * (85 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l20_rb[8 * (205 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l21_rb[8 * (505 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    float la0_l22_rb[8 * (1195 + 2 * NAM_A2FULL_MAX_BUFFER_SIZE) * 1] __attribute__((aligned(16)));
    int la0_l0_wp;
    int la0_l1_wp;
    int la0_l2_wp;
    int la0_l3_wp;
    int la0_l4_wp;
    int la0_l5_wp;
    int la0_l6_wp;
    int la0_l7_wp;
    int la0_l8_wp;
    int la0_l9_wp;
    int la0_l10_wp;
    int la0_l11_wp;
    int la0_l12_wp;
    int la0_l13_wp;
    int la0_l14_wp;
    int la0_l15_wp;
    int la0_l16_wp;
    int la0_l17_wp;
    int la0_l18_wp;
    int la0_l19_wp;
    int la0_l20_wp;
    int la0_l21_wp;
    int la0_l22_wp;
    int _unused;
} nam_a2full_state_t;

/* One running engine: its hot buffers, plus the capture and ring state it
   uses. Hot: e.g. DTCM on Cortex-M7. Fields are private. */
typedef struct NAM_ALIGNED(32) nam_a2full_t {
    float la0_hbuf[8 * (15 + NAM_A2FULL_MAX_BUFFER_SIZE)] NAM_ALIGNED(32); /* head accumulator + 15 history columns */
    float la0_hout[1 * NAM_A2FULL_MAX_BUFFER_SIZE];
    const nam_a2full_weights_t* weights;
    nam_a2full_state_t* state;
} nam_a2full_t;

/* Bind an instance to a capture and a ring state, and reset it. */
void nam_a2full_init(nam_a2full_t* inst, const nam_a2full_weights_t* weights, nam_a2full_state_t* state);

/* Switch the capture an instance uses; call nam_a2full_reset and prewarm afterwards. */
void nam_a2full_set_weights(nam_a2full_t* inst, const nam_a2full_weights_t* weights);

/* Clear the instance's signal state (ring buffers and head history). */
void nam_a2full_reset(nam_a2full_t* inst);

/* Run NAM_A2FULL_PREWARM_SAMPLES of silence through the instance, so its output
   starts without a transient. Call after nam_a2full_init or nam_a2full_reset, once the
   capture is loaded; not real-time (~NAM_A2FULL_PREWARM_SAMPLES samples of work). */
void nam_a2full_prewarm(nam_a2full_t* inst);

/* Process num_frames (<= NAM_A2FULL_MAX_BUFFER_SIZE) of audio */
void nam_a2full_process(nam_a2full_t* inst, const float* const* input, float* const* output, int num_frames);

/* Pack a flat weight array (C++ set_weights_ order) into dst.
   Returns 0 on success, -1 on weight count mismatch (dst untouched). */
int nam_a2full_load_weights(nam_a2full_weights_t* dst, const float* weights, int num_weights);

#endif /* NAM_A2FULL_H */